import type { AnalysisResult } from "../types/analysis";

export function formatReport(result: AnalysisResult): string {
  const divider = "─".repeat(60);
  const date = new Date(result.fetchedAt).toLocaleString();

  const techList = result.techStack.length
    ? result.techStack.map((t) => `  • ${t.name} (${t.category}, ${t.confidence} confidence)`).join("\n")
    : "  No technologies detected";

  const seoSummary = result.seoChecks
    .map((c) => `  [${c.status.toUpperCase().padEnd(7)}] ${c.label}: ${c.detail}`)
    .join("\n");

  const ux = result.ux;
  const uxSummary = [
    `  Call-to-Action:      ${ux.hasCTA ? `Yes (${ux.ctaCount} detected)` : "Not detected"}`,
    `  Lead Capture Form:   ${ux.hasForms ? `Yes (${ux.formCount} form${ux.formCount !== 1 ? "s" : ""})` : "Not detected"}`,
    `  Social Proof:        ${ux.hasSocialProof ? "Detected" : "Not detected"}`,
    `  Trust Signals:       ${ux.hasTrustSignals ? "Detected" : "Not detected"}`,
    `  Contact Info:        ${ux.hasContactInfo ? "Found" : "Not found"}`,
    `  Mobile Responsive:   ${ux.mobileReady ? "Yes" : "No"}`,
  ].join("\n");

  const weak = result.weakPoints.length
    ? result.weakPoints.map((w) => `  • ${w}`).join("\n")
    : "  No significant weak points identified";

  const recs = result.recommendations.length
    ? result.recommendations.map((r, i) => `  ${i + 1}. ${r}`).join("\n")
    : "  No recommendations at this time";

  return `WEBSITE ANALYSIS REPORT
${divider}
URL:       ${result.url}
Analyzed:  ${date}
${divider}

OVERVIEW
  Title:       ${result.overview.title || "(none)"}
  Description: ${result.overview.description || "(none)"}
  Language:    ${result.overview.language || "unknown"}
  Page size:   ${result.overview.pageLoadHint}

${divider}
DETECTED TECH STACK
${techList}

${divider}
SEO AUDIT
${seoSummary}

${divider}
CONVERSION / UX SIGNALS
${uxSummary}

${divider}
WEAK POINTS
${weak}

${divider}
RECOMMENDATIONS
${recs}

${divider}
Generated by Explain This Website
`;
}
